version: '3.8'

services:
  server:
    build:
      context: ./server/
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8888:8080
      - 2345:2345
    volumes:
      - ./server/:/app
    tty: true  ## tty: trueを追加
  client:
    build:
      context: ./client/
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./client/:/app
    ports:
      - 3434:3000
    tty: true  ## tty: trueを追加
